// File: Cmd_IOBOard.h
// Author: Oliver Barth / Neobotix

#ifndef CMD_IOBOARD_INCLUDEDEF_H
#define CMD_IOBOARD_INCLUDEDEF_H

enum CMD_IOBOARD
{
	CMD_IOBOARD_CONNECT,
	CMD_IOBOARD_DISCONNECT,
	CMD_IOBOARD_GETDIGIN,
	CMD_IOBOARD_SETDIGOUT,
	CMD_IOBOARD_GETANALOGIN,
	CMD_IOBOARD_GETGYROVAL,
	CMD_IOBOARD_ZEROGYRO,
	CMD_IOBOARD_GETJOYVAL,
	CMD_IOBOARD_GETVBATT,
	CMD_IOBOARD_GETSTATUS,
	CMD_IOBOARD_SETCTRLPARA,
	CMD_IOBOARD_GETCTRLPARA,
	CMD_IOBOARD_UNKNOWN
};

// Ben Adler: add the canbus-IDs for the IOBoard:
#define CAN_ID_IO_CMD 0x0101
#define CAN_ID_IO_REPLY 0x0100

#endif

